FROM httpd:alpine

COPY configuration/htpasswd /usr/local/apache2/conf/.htpasswd
COPY configuration/httpd.conf /usr/local/apache2/conf/httpd.conf
RUN chmod 644 /usr/local/apache2/conf/.htpasswd
RUN chmod 644 /usr/local/apache2/conf/httpd.conf
RUN chown root:root /usr/local/apache2/conf/.htpasswd
RUN chown root:root /usr/local/apache2/conf/httpd.conf
