---
- name: "Create {{ secgrp.name }} security group"
  os_security_group:
    state: present
    name: "{{ secgrp.name }}"

- name: "Create {{ secgrp.name }} security group rule for ping"
  os_security_group_rule:
    security_group: "{{ secgrp.name }}"
    protocol: icmp
    remote_ip_prefix: "{{ item }}"
  loop: "{{ secgrp.remote_ip_prefix }}"

- name: "Create {{ secgrp.name }} security group rule for SSH"
  os_security_group_rule:
    security_group: "{{ secgrp.name }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: "{{ item }}"
  loop: "{{ secgrp.remote_ip_prefix }}"

- name: "Create {{ secgrp.name }} security group rule for ONAP Docker registry"
  os_security_group_rule:
    security_group: "{{ secgrp.name }}"
    protocol: tcp
    port_range_min: 10001
    port_range_max: 10001
    remote_ip_prefix: "{{ item }}"
  loop: "{{ secgrp.local_ip_prefix }}"
