---
- hosts: all
- name: Install NFS
  hosts: all
  become: yes
  roles:
    - role: setup_nfs
- name: Set up bastion node for ONAP Docker registry
  hosts: "nfs0"
  become: yes
  roles:
    - role: create_bastion
      destination: "{{ nexus }}"
- name: Add bastion information to the cluster nodes
  hosts: all
  become: yes
  tasks:
    - name: Add cluster hostnames to /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars['nfs0']['ansible_default_ipv4']['address'] }} {{ item }}"
      loop:
        - "nexus3.onap.org"
- name: Install Docker
  become: yes
  hosts: control,workers
  roles:
    - role: setup_docker
- name: Deploy k8s
  hosts: operator0
  roles:
    - role: setup_k8s
- name: Download OOM
  hosts: operator0
  tasks:
    - name: Clone OOM
      git:
        repo: "https://git.onap.org/oom"
        dest: "{{ oom_dir }}"
        version: "master"
- name: Install Helm
  hosts: operator0
  roles:
    - role: setup_helm
- name: Install cert-manager and prometheus
  hosts: operator0
  roles:
    - role: deps
- name: Deploy sm-onap
  hosts: operator0
  roles:
    - role: oom
