---
- name: Install NFS
  hosts: all
  become: yes
  roles:
    - role: setup_nfs
- name: Set up bastion node for ONAP Docker registry
  hosts: "control0"
  become: yes
  roles:
    - role: create_bastion
      destination: "{{ nexus }}"
- name: Add bastion information to the cluster nodes
  hosts: all
  become: yes
  tasks:
    - name: Add cluster hostnames to /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars['control0']['ansible_default_ipv4']['address'] }} {{ item }}"
      loop:
        - "nexus3.onap.org"
