---
- name: Deploy kubernetes with RKE
  include_tasks: rke.yml

- name: Create k8s directory
  file:
    name: "{{ ansible_user_dir }}/.kube"
    state: directory
    mode: '0700'

- name: Set k8s config
  command: "mv {{ ansible_user_dir }}/kube_config_cluster.yml {{ ansible_user_dir }}/.kube/config"
  when: rke_run and rke_run.rc == 0

- name: Install kubectl
  include_tasks: kubectl.yml
