#!/usr/bin/python3
#  ============LICENSE_START=======================================================
#  ONAP - SO
#  ================================================================================
#  Copyright (C) 2020 Huawei Technologies Co., Ltd. All rights reserved.
#  ================================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=========================================================

import sys
import argparse
import json

import conf
import install_n_e_sw


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("--swToBeInstalled", help="The NE software to be installed", required=True)
    parser.add_argument("--neIdentifier", help="The NE where the software can be installed", required=True)

    args = parser.parse_args()

    _, ret_value = install_n_e_sw.install(args.swToBeInstalled, args.neIdentifier)
    print(json.dumps(ret_value))

    if ret_value["result"] == conf.REQ_SUCCESS:
        sys.exit(conf.RET_CODE_SUCCESS)
    else:
        sys.exit(conf.RET_CODE_FAILURE)


if __name__ == '__main__':
    main()
