#!/usr/bin/python3
#  ============LICENSE_START=======================================================
#  ONAP - SO
#  ================================================================================
#  Copyright (C) 2020 Huawei Technologies Co., Ltd. All rights reserved.
#  ================================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#       http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=========================================================

import sys
import argparse
import json

import conf
import ems_util
import sw_fallback


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("--filter", help="To describe properties of the NEs to be selected", required=True)

    args = parser.parse_args()

    ne_info_list = ems_util.get_ne_info_list_from_db(args.filter)

    ret_value = sw_fallback.fallback(ne_info_list)
    print(json.dumps(ret_value))

    if ret_value["result"] == conf.RESULT_SUCCESS:
        sys.exit(conf.RET_CODE_SUCCESS)
    else:
        sys.exit(conf.RET_CODE_FAILURE)


if __name__ == '__main__':
    main()
