#!/usr/bin/python3
#  ============LICENSE_START=======================================================
#  ONAP - SO
#  ================================================================================
#  Copyright (C) 2020 Huawei Technologies Co., Ltd. All rights reserved.
#  ================================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#       http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=========================================================

import sys
import json

import conf
import upgrade_pre_check


def main():
    # {{pnfName}} {{oldSwVersion}} {{targetSwVersion}} {{ruleName}} {{additionalDataFile}}

    if len(sys.argv) < 5:
        ret_value = {
            "result": conf.RESULT_FAILURE,
            "reason": "Missing parameters"
        }
        print(json.dumps(ret_value))
        sys.exit(conf.RET_CODE_FAILURE)
    else:
        pnf_name = sys.argv[1]
        old_sw_version = sys.argv[2]
        target_sw_version = sys.argv[3]
        rule_name = sys.argv[4]
        additional_data_file = None

    if len(sys.argv) >= 6:
        additional_data_file = sys.argv[5]

    ret_value = upgrade_pre_check.pre_check(
        pnf_name, old_sw_version, target_sw_version, rule_name, additional_data_file)
    print(json.dumps(ret_value))

    if ret_value["result"] == conf.RESULT_SUCCESS:
        sys.exit(conf.RET_CODE_SUCCESS)
    else:
        sys.exit(conf.RET_CODE_FAILURE)


if __name__ == '__main__':
    main()
