---
roles:
  - name: geerlingguy.ansible
    version: 2.1.0

collections:
  - name: ansible.posix
    version: 1.4.0
  - name: community.crypto
    version: 2.2.1
  - name: openstack.cloud
    version: 1.6.0
