---
- name: Download helm
  get_url:
    url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "/tmp"

- name: Unarchive helm
  unarchive:
    src: "/tmp/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Copy helm binary to $PATH
  become: yes
  copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/local/bin/"
    remote_src: yes
    mode: '0555'

- name: Check if Helm Push plugin is installed
  kubernetes.core.helm_plugin_info:
    plugin_name: push
  register: push_plugin_info

- name: Install Helm Push plugin
  command: helm plugin install --version 0.9.0 https://github.com/chartmuseum/helm-push.git
  when: push_plugin_info.plugin_list | length == 0

- name: Install Helm OOM Deploy plugin
  kubernetes.core.helm_plugin:
    plugin_path: "{{ oom_dir }}/kubernetes/helm/plugins/deploy"
    state: present

- name: Install Helm OOM Undeploy plugin
  kubernetes.core.helm_plugin:
    plugin_path: "{{ oom_dir }}/kubernetes/helm/plugins/undeploy"
    state: present
