---
- name: Setup helm
  include_tasks: helm.yml

- name: Setup chartmuseum
  include_tasks: cm.yml

- name: Add local Helm repository
  kubernetes.core.helm_repository:
    name: "local"
    repo_url: "http://127.0.0.1:{{ chartmuseum_port }}"
    state: present
