---
- name: Setup Docker repo and packages
  include_tasks: packages.yml

- name: Add user to docker group
  user:
    name: "{{ local_user }}"
    groups: docker
    append: yes
  when: local_user is defined

- name: Make sure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Configure Docker
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_config | to_nice_json }}"
    mode: 0600
    backup: true
  when: docker_config is defined
  notify:
    - restart docker
