---
- name: Setup cert-manager
  include_tasks: cert-manager.yml

- name: Setup strimzi
  include_tasks: strimzi.yml
  when: strimzi_enabled

- name: Setup MetalLB
  include_tasks: metallb.yml
  when: metallb_enabled

- name: Setup Prometheus
  include_tasks: prometheus.yml
  when: prometheus_enabled

- name: Setup Istio
  include_tasks: istio.yml
  when: istio_enabled
