- name: Download cert-manager
  get_url:
    url: "https://github.com/jetstack/cert-manager/releases/download/v{{ cert_manager_version }}/cert-manager.yaml"
    dest: "/tmp"
    mode: '0400'

- name: Deploy cert-manager
  kubernetes.core.k8s:
    src: /tmp/cert-manager.yaml
    state: present

- name: Add MetalLB Helm repository
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Add prometheus Helm repository
  kubernetes.core.helm_repository:
    name: prometheus
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Copy MetalLB override file
  template:
    src: "metallb-values.yaml.j2"
    dest: "/tmp/metallb-values.yaml"
    mode: '0400'

- name: Deploy MetalLB charts
  kubernetes.core.helm:
    name: metallb
    chart_version: "{{ metallb_version }}"
    chart_ref: metallb/metallb
    release_namespace: metallb
    create_namespace: true
    values_files:
      - /tmp/metallb-values.yaml

- name: Deploy Prometheus charts
  kubernetes.core.helm:
    name: prometheus
    chart_version: "{{ prometheus_version }}"
    chart_ref: prometheus/kube-prometheus-stack
    release_namespace: prometheus
    create_namespace: true
