- name: Destroy keypair
  os_keypair:
    state: absent
    name: "{{ keypair.name }}"

- name: Destroy local keypair
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - "~/.ssh/{{ keypair.name }}.pub"
    - "~/.ssh/{{ keypair.name }}"
