- name: Build OOM charts
  make:
    chdir: "{{ oom_dir }}/kubernetes"
    target: all
    params:
      SKIP_LINT: "TRUE"

- name: Create ONAP namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: onap
        labels:
          istio-injection: enabled
  when: istio_enabled

- name: Create ONAP namespace
  kubernetes.core.k8s:
    name: onap
    api_version: v1
    kind: Namespace
    state: present
  when: not istio_enabled

- name: Deploy sm-onap
  command:
    cmd: "helm deploy onap local/onap --namespace onap --set global.masterPassword=scrtPasswd -f {{ oom_dir }}/kubernetes/onap/resources/overrides/sm-onap.yaml"
