#!/bin/bash

set -o xtrace

source /var/onap/functions
source /var/onap/asserts

src_folder=$git_src_folder/portal
policy_repos=("sdk")

# clone_all_portal_repos() - Function that clones Portal source repo.
function clone_all_portal_repos {
    clone_repo portal $src_folder

    for dirc in ${policy_repos[@]}; do
        clone_repo portal/$dirc $src_folder/$dirc
    done
}

# compile_all_portal_repos() - Function that compiles Portal source repo.
function compile_all_portal_repos {
    compile_src $src_folder

    for dirc in ${policy_repos[@]}; do
        compile_src $src_folder/$dirc
    done
}

# get_portal_images() - Function to get Portal images.
function get_portal_images {
if [[ "$build_image" == "True" ]]; then
        install_maven

        clone_repo ecompsdkos $src_folder/ecompsdkos
        clone_repo "ui/dmaapbc" $src_folder/dmaapbc
        pushd $src_folder/deliveries
        chmod +x *.sh
        export MVN=$(which mvn)
        export GLOBAL_SETTINGS_FILE=/usr/share/maven3/conf/settings.xml
        export SETTINGS_FILE=$HOME/.m2/settings.xml
        bash run.sh
        compile_src $src_folder/ecomp-portal-widget-ms
        build_docker_image $src_folder/ecomp-portal-widget-ms
    else
        pull_openecomp_image portaldb ecompdb:portal
        pull_openecomp_image portalapps ep:1610-1
    fi

}

# install_mariadb() - Pull and create a MariaDB container
function install_mariadb {
    is_package_installed docker-ce || install_docker
    docker pull mariadb
    docker create --name data_vol_portal -v /var/lib/mysql mariadb
}

# install_portal() - Function that installs the source code of Portal
function install_portal {
    install_docker
    docker rm -f ecompdb_portal
    docker rm -f 1610-1
    pushd $src_folder/deliveries


    chmod +x new_start.sh
    chmod +x new_stop.sh
    chmod +x dbstart.sh
    mkdir -p /PROJECT/OpenSource/UbuntuEP/logs
    install_package unzip
    unzip -o etc.zip -d /PROJECT/OpenSource/UbuntuEP/

    bash dbstart.sh
    bash new_start.sh

    sleep 180

    if [ ! -e /opt/config/boot.txt ]; then
        install_package mysql-client
        mysql -u root -p'Aa123456' -h $IP_ADDRESS < Apps_Users_OnBoarding_Script.sql
        echo "yes" > /opt/config/boot.txt
    fi
    popd
}

# init_portal() - Function that initialize Portal services
function init_portal {
    clone_all_portal_repos
    if [[ "$compile_repo" == "True" ]]; then
        compile_all_portal_repos
    fi
    install_mariadb
    get_portal_images
    install_portal
}
