---
- name: Create infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - openstack/create_devstack_network
    - openstack/create_devstack_securitygroup
    - openstack/create_devstack_keypair
    - openstack/create_devstack_hosts
