---
- name: Destroy infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - role: destroy_hosts
      hosts: "{{ cluster.hosts }}"
    - role: destroy_hosts
      hosts: "{{ operation.hosts }}"
    - role: destroy_hosts
      hosts: "{{ openstack.hosts }}"
    - destroy_keypair
    - destroy_network
    - destroy_securitygroup
