---
- name: Destroy infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - role: openstack/destroy_devstack_hosts
      hosts: "{{ cluster.hosts }}"
    - openstack/destroy_devstack_keypair
    - openstack/destroy_devstack_network
    - openstack/destroy_devstack_securitygroup
