---
- name: Create host
  os_server:
    state: present
    name: "{{ host.name }}"
    image: "{{ host.image }}"
    flavor: "{{ host.flavor }}"
    key_name: "{{ host.keypair }}"
    network: "{{ host.network }}"
    security_groups:
      - "{{ host.securitygroup }}"
    auto_ip: "{{ host.auto_ip | default(true) }}"
    boot_from_volume: true
    terminate_volume: true
    volume_size: "{{ host.volume_size | default(10) }}"
