# -*- mode: ruby -*-
# -*- coding: utf-8 -*-

host_ip = "192.168.121.1"
operator_key = "${HOME}/.ssh/onap-key"
vagrant_user = "vagrant"
vagrant_password = "vagrant"

vm_memory = 2 * 1024
vm_cpus = 1
vm_box = "generic/ubuntu1804"

operation = { name: 'operator', hostname: 'operator', ip: '172.17.0.254' }
cluster = [
  { name: 'control', hostname: 'control', ip: '172.17.0.100' },
  { name: 'worker', hostname: 'worker', ip: '172.17.0.101' }
]

all = cluster.dup << operation

$add_to_docker_group = <<-SCRIPT
  USER="$1"
  usermod -aG docker "$USER"
SCRIPT

$deploy_key = <<-SCRIPT
  KEY="$1"
  USER="$2"
  PASS="$PASSWORD"
  IPS="$3"
  for ip in $IPS; do
    sshpass -p "$PASS" ssh-copy-id -o StrictHostKeyChecking=no -i "$KEY" "${USER}@${ip}"
  done
SCRIPT

$link_dotfiles = <<-SCRIPT
  for rc in /vagrant/dot_*; do
    ln -sf "$rc" "${HOME}/.${rc##*dot_}"
  done
SCRIPT

Vagrant.configure('2') do |config|
  all.each do |machine|
    config.vm.define machine[:name] do |config|
      config.vm.box = vm_box
      config.vm.hostname = machine[:hostname]

      config.vm.provider :virtualbox do |v|
        v.name = machine[:name]
        v.memory = vm_memory
        v.cpus = vm_cpus
      end

      config.vm.provider :libvirt do |v|
        v.memory = vm_memory
        v.cpus = vm_cpus
      end

      config.vm.network :private_network, ip: machine[:ip]
      config.vm.provision :shell, inline: <<-SHELL
        rm -f /etc/resolv.conf # drop its dynamic management by systemd-resolved
        echo nameserver #{host_ip} | tee /etc/resolv.conf
      SHELL

      if machine[:name] == 'control'
        config.vm.provision :shell, path: "../../tools/dublin/imported/openstack-k8s-controlnode.sh"
        config.vm.provision :shell, inline: $add_to_docker_group, args: vagrant_user
      end

      if machine[:name] == 'worker'
        config.vm.provision :shell, path: "../../tools/dublin/imported/openstack-k8s-workernode.sh"
        config.vm.provision :shell, inline: $add_to_docker_group, args: vagrant_user
      end

      if machine[:name] == 'operator'
        config.vm.synced_folder "../../tools/config", "/vagrant", type: "rsync"

        config.vm.provision :shell, run: "always", inline: $link_dotfiles
        config.vm.provision :shell, run: "always", privileged: false, inline: $link_dotfiles

        config.vm.provision :shell, path: "../../tools/dublin/get_rke.sh"

        config.vm.provision :shell, inline: <<-SHELL
          apt-get update
          apt-get install sshpass
        SHELL
        config.vm.provision :shell, privileged: false, inline: <<-SHELL
          ssh-keygen -q -b 4096 -t rsa -f #{operator_key} -N ""
        SHELL

        ips = ""
        cluster.each { |node| ips << node[:ip] << " " }
        config.vm.provision :shell do |s|
          s.privileged = false
          s.inline = $deploy_key
          s.args = [operator_key, vagrant_user, ips]
          s.env = {'PASSWORD': vagrant_password}
        end
      end
    end
  end
end
